// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9Kj0IZWHc3l4ndh90ixn9WgWemnYBrI',
    appId: '1:369528462326:web:e3cf5de86c4dfd739405d7',
    messagingSenderId: '369528462326',
    projectId: 'smart-washroom-hygiene-s-4af6a',
    authDomain: 'smart-washroom-hygiene-s-4af6a.firebaseapp.com',
    storageBucket: 'smart-washroom-hygiene-s-4af6a.firebasestorage.app',
    measurementId: 'G-0RLGZVTGSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-Qul54OseD0LoPaxy7yVkhI_diclUN4',
    appId: '1:369528462326:android:db7a44485a43d0df9405d7',
    messagingSenderId: '369528462326',
    projectId: 'smart-washroom-hygiene-s-4af6a',
    storageBucket: 'smart-washroom-hygiene-s-4af6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANudccMWvisJD3BKFBYJub8h5TEefH3ZE',
    appId: '1:369528462326:ios:b43c61c7fbad0a329405d7',
    messagingSenderId: '369528462326',
    projectId: 'smart-washroom-hygiene-s-4af6a',
    storageBucket: 'smart-washroom-hygiene-s-4af6a.firebasestorage.app',
    iosBundleId: 'com.example.cleanerApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANudccMWvisJD3BKFBYJub8h5TEefH3ZE',
    appId: '1:369528462326:ios:b43c61c7fbad0a329405d7',
    messagingSenderId: '369528462326',
    projectId: 'smart-washroom-hygiene-s-4af6a',
    storageBucket: 'smart-washroom-hygiene-s-4af6a.firebasestorage.app',
    iosBundleId: 'com.example.cleanerApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt9Kj0IZWHc3l4ndh90ixn9WgWemnYBrI',
    appId: '1:369528462326:web:94022ad41407fffd9405d7',
    messagingSenderId: '369528462326',
    projectId: 'smart-washroom-hygiene-s-4af6a',
    authDomain: 'smart-washroom-hygiene-s-4af6a.firebaseapp.com',
    storageBucket: 'smart-washroom-hygiene-s-4af6a.firebasestorage.app',
    measurementId: 'G-DCSK7SVQNX',
  );
}
